/**
 * @module SessionContext
 *
 * Immutable value object representing all resolved dependencies for a single
 * Voice Engine V2 call session.
 *
 * ## Immutability
 * `SessionContext` is frozen via `Object.freeze` immediately after creation
 * by `createSessionContext`. No field may be replaced after that point.
 *
 * ## Rules
 * - No OpenAI imports.
 * - No Exotel imports.
 * - No transport logic.
 * - No WebSocket logic.
 * - No business logic — this is a pure data carrier.
 */

import type { IVoiceEngine } from '../engine/VoiceEngine.js';
import type { ITransportGateway } from '../transport/TransportGateway.js';
import type { IMediaSession } from '../media/MediaSession.js';
import type { VoiceEngineRuntime } from '../bootstrap/Bootstrap.js';
import type { SessionId, CallSid, CampaignId, Timestamp, Nullable } from '../types/index.js';

// ─── Metadata ─────────────────────────────────────────────────────────────────

/**
 * Arbitrary key/value pairs attached to a session at creation time.
 * Values must be JSON-serialisable. Frozen after construction.
 */
export interface SessionMetadata {
  readonly [key: string]: unknown;
}

// ─── Public Interface ─────────────────────────────────────────────────────────

/**
 * Immutable snapshot of all resolved dependencies for one V2 call session.
 *
 * All fields are readonly. The object is sealed with `Object.freeze`
 * by `createSessionContext` before being returned to the caller.
 *
 * `callSid` and `phone` are `null` until the telephony layer provides them
 * (e.g. after Exotel confirms the outbound call). `mediaSession` is `null`
 * until a WebSocket connection is established and the engine creates the
 * per-call session internally.
 */
export interface SessionContext {
  /**
   * Stable, unique identifier for this session.
   * Generated by `SessionFactory` and never mutated.
   */
  readonly sessionId: SessionId;

  /**
   * Exotel (or other provider) call SID.
   * Null until `V2SessionCoordinator.attachCallSid()` is called.
   */
  readonly callSid: Nullable<CallSid>;

  /**
   * E.164 phone number of the remote party.
   * Null until `V2SessionCoordinator.attachPhone()` is called.
   */
  readonly phone: Nullable<string>;

  /**
   * Campaign identifier this session is running under.
   * Set at session creation time and never changed.
   */
  readonly campaignId: CampaignId;

  /**
   * Unix millisecond timestamp when this context was created.
   */
  readonly createdAt: Timestamp;

  /**
   * The Voice Engine bootstrap runtime (config, DI container, resolver,
   * health registry) that underpins this session's engine instance.
   */
  readonly runtime: VoiceEngineRuntime;

  /**
   * The fully wired `IVoiceEngine` instance for this session.
   * In the CREATED or READY state at context construction time.
   */
  readonly voiceEngine: IVoiceEngine;

  /**
   * The `ITransportGateway` that will own inbound WebSocket connections
   * for this session.
   */
  readonly transportGateway: ITransportGateway;

  /**
   * The per-call `IMediaSession` coordinator.
   * Null until the engine creates it upon WebSocket connection.
   */
  readonly mediaSession: Nullable<IMediaSession>;

  /**
   * Arbitrary caller-supplied metadata attached at session creation.
   * Frozen after construction.
   */
  readonly metadata: Readonly<SessionMetadata>;
}

// ─── Construction Input ───────────────────────────────────────────────────────

/**
 * All fields required to construct a `SessionContext`.
 * Supplied by `SessionFactory.createSession()`.
 */
export interface SessionContextInput {
  /** Unique session identifier. */
  readonly sessionId: SessionId;
  /** Initial call SID — may be null if not yet assigned. */
  readonly callSid: Nullable<CallSid>;
  /** Initial phone number — may be null if not yet known. */
  readonly phone: Nullable<string>;
  /** Campaign identifier. */
  readonly campaignId: CampaignId;
  /** Creation timestamp (Unix ms). */
  readonly createdAt: Timestamp;
  /** Bootstrap runtime for this session's engine. */
  readonly runtime: VoiceEngineRuntime;
  /** Wired voice engine instance. */
  readonly voiceEngine: IVoiceEngine;
  /** Transport gateway for this session. */
  readonly transportGateway: ITransportGateway;
  /** Per-call media session — null at creation time. */
  readonly mediaSession: Nullable<IMediaSession>;
  /** Optional caller metadata. */
  readonly metadata?: SessionMetadata;
}

// ─── Factory Function ─────────────────────────────────────────────────────────

/**
 * Constructs and freezes a `SessionContext` from the provided input.
 *
 * The returned object is passed through `Object.freeze` and may not be
 * mutated after this call. The `metadata` sub-object is also frozen.
 *
 * @param input - All required session fields.
 * @returns An immutable `SessionContext`.
 *
 * @throws {Error} if `sessionId` or `campaignId` are empty strings.
 *
 * @example
 * ```typescript
 * const ctx = createSessionContext({
 *   sessionId: 'sess-abc123',
 *   callSid: null,
 *   phone: null,
 *   campaignId: 'camp-xyz',
 *   createdAt: Date.now(),
 *   runtime,
 *   voiceEngine,
 *   transportGateway,
 *   mediaSession: null,
 * });
 * ```
 */
export function createSessionContext(
  input: SessionContextInput
): Readonly<SessionContext> {
  if (!input.sessionId.trim()) {
    throw new Error('SessionContext: sessionId must be a non-empty string.');
  }
  if (!input.campaignId.trim()) {
    throw new Error('SessionContext: campaignId must be a non-empty string.');
  }

  const ctx: SessionContext = {
    sessionId:        input.sessionId,
    callSid:          input.callSid,
    phone:            input.phone,
    campaignId:       input.campaignId,
    createdAt:        input.createdAt,
    runtime:          input.runtime,
    voiceEngine:      input.voiceEngine,
    transportGateway: input.transportGateway,
    mediaSession:     input.mediaSession,
    metadata:         Object.freeze({ ...(input.metadata ?? {}) }),
  };

  return Object.freeze(ctx);
}
