/**
 * @module V2CallActivator
 *
 * Activates a pre-registered V2 session when the Exotel WebSocket connects.
 *
 * ## Responsibility
 * Bridges the gap between `SessionFactory.createSession()` (which builds a
 * session context with stub components) and `RuntimeIntegration.start()`
 * (which opens the real provider connection and starts the audio pipeline).
 *
 * ## Conversation Engine wiring
 * Every live call now uses the full Conversation Policy Engine via
 * `policyContext`. This means:
 *  - System prompt is generated by ConversationPolicyBuilder (all policy
 *    sections: stage objectives, speaking style, emotional adaptation, etc.)
 *  - After every agent turn, the state machine advances and OpenAI receives
 *    fresh stage-specific instructions via session.update.
 *  - The conversation follows the structured funnel:
 *    GREETING → RAPPORT → DISCOVERY → QUALIFICATION →
 *    PRESENTATION → OBJECTION_HANDLING → CLOSING
 *
 * ## When to call
 * Call `activateV2Session(ctx)` immediately after
 * `ctx.transportGateway.accept()` succeeds in the V2 router.  The function
 * is async — the caller should fire-and-forget with `.catch()` logging.
 *
 * ## Cleanup
 * The `RuntimeIntegration` is stopped automatically when the transport session
 * emits `transport.disconnected`.  No manual cleanup is required by the caller.
 */

import { storage } from '../../storage.js';
import { IntegrationFactory } from '../integration/IntegrationFactory.js';
import { createAudioEngine } from '../audio-engine/AudioEngineFactory.js';
import type { SessionContext } from './SessionContext.js';
import type { IRuntimeIntegration } from '../integration/RuntimeIntegration.js';
import type { OpenAIRealtimeProvider } from '../providers/openai/OpenAIRealtimeProvider.js';
import type { TransportDisconnectedEvent } from '../transport/TransportEvents.js';
import { attachOneCallAudioCapture } from '../diagnostics/OneCallAudioCapture.js';
import type { PolicyConversationContext, CallerMetadata } from '../conversation/index.js';
import { normalizePhoneNumber } from '../../phoneUtils.js';
import { CallTrace } from '../debug/CallTrace.js';

// ── One-shot audio capture flag ────────────────────────────────────────────────
// Set to true after the first call so the capture is never attached twice.
let _captureAttached = false;

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Activates the Voice Engine V2 pipeline for a connected Exotel WebSocket.
 *
 * 1. Loads campaign, user, and lead data from MongoDB.
 * 2. Builds a `PolicyConversationContext` to wire the full Conversation Engine.
 * 3. Opens a real `IOpenAIRealtimeSession` via the DI-registered provider.
 * 4. Creates a fresh `AudioEngine` for this call's pipeline.
 * 5. Assembles the full `RuntimeIntegration` via `IntegrationFactory`.
 * 6. Starts the integration — opens the OpenAI WebSocket, attaches
 *    `TurnDiagnosticsCollector`, and starts inbound/outbound audio flows.
 * 7. Registers a `transport.disconnected` listener to stop the integration
 *    when the Exotel WebSocket closes.
 *
 * @param ctx - The pre-registered `SessionContext` from `createSession()`.
 * @returns The started `IRuntimeIntegration`.
 * @throws If `ctx.mediaSession` is null or the integration fails to start.
 */
export async function activateV2Session(ctx: SessionContext): Promise<IRuntimeIntegration> {
  console.log(`[V2 TRACE] 4. activateV2Session() entered  sessionId=${ctx.sessionId}  campaignId=${ctx.campaignId}`);
  CallTrace.create(ctx.sessionId);

  if (!ctx.mediaSession) {
    throw new Error(
      `V2CallActivator: SessionContext ${ctx.sessionId} has no MediaSession — cannot activate.`
    );
  }

  const logger = ctx.runtime.resolver.logger().child({
    component: 'V2CallActivator',
    sessionId: ctx.sessionId,
  });

  logger.info('Activating V2 session — loading campaign data and wiring Conversation Engine', {
    sessionId: ctx.sessionId,
    campaignId: ctx.campaignId,
  });

  // ── Step 1: Load campaign, user, and lead data ──────────────────────────────
  //
  // We need:
  //  - campaign  → goal, script, KB, additionalContext
  //  - user      → agentName (firstName), companyName
  //  - lead      → caller firstName, company (looked up by phone)
  //
  // All three are attempted independently — a failure on any one degrades
  // gracefully; the call still proceeds with defaults.

  let policyContext: PolicyConversationContext | null = null;
  let fallbackInstructions = '';

  try {
    const campaign = await storage.getCampaign(ctx.campaignId);

    if (campaign) {
      const c = campaign as any;

      // ── Campaign fields ──────────────────────────────────────────────────────
      const goalType          = ((c.goal || 'sales') as string).trim().toLowerCase();
      const campaignName      = ((c.name || '') as string).trim();
      const additionalContext = ((c.additionalContext || '') as string).trim();
      // Use only the human-written script (not ai_generated_script) as the
      // reference — the AI-generated one is a verbose pitch meant for human
      // agents and causes the AI to open the call with a full sales monologue.
      const script            = ((c.script || '') as string).trim();

      // Build a call OBJECTIVE from goalType — tells AI *why* it is calling.
      // goalType is the type-tag ("sales"/"appointment"/"survey"/"support").
      // We convert it to a clear action phrase so the AI knows what to achieve,
      // rather than getting a company-history string as its "goal".
      const goalActionMap: Record<string, string> = {
        'sales':       'present and sell',
        'appointment': 'book a site visit or appointment for',
        'survey':      'gather feedback on',
        'support':     'resolve support queries about',
      };
      const goalAction = goalActionMap[goalType] || 'discuss';
      const callObjective = campaignName
        ? `${goalAction} ${campaignName}`
        : 'speak with the prospect about our offering';

      // Full goal description: objective + company background as context.
      const goalDescription = additionalContext
        ? `${callObjective}. Background: ${additionalContext}`
        : callObjective;

      // Campaign type for persona shaping
      const campaignType = goalType as 'sales' | 'support' | 'survey';

      // Language — default English; can be extended per-campaign later
      const language = ((c.language || 'English') as string).trim() || 'English';

      // Knowledge base — all text chunks as individual strings for the KB policy
      const kbChunks: string[] = [
        ...(c.knowledgeBaseTexts || [] as string[]).filter(Boolean),
        ...(c.knowledgeBaseFiles || [] as any[])
          .map((f: any): string | undefined => f.extractedText as string | undefined)
          .filter((t: string | undefined): t is string => !!t && t.trim().length > 0),
      ];

      // ── Extract agent name / company from script as a fallback ─────────────
      // Many campaigns embed the agent's name and company in the script opener,
      // e.g. "Hi, I am Amit calling from Marine Real Estate Company."
      // Parse these out so even minimally-filled campaigns sound correct.
      let scriptAgentName: string | null = null;
      let scriptCompanyName: string | null = null;
      if (script) {
        const agentMatch = script.match(
          /(?:I am|I'm|this is)\s+([A-Z][a-zA-Z]+)\s+(?:calling|from)/i
        );
        scriptAgentName = agentMatch?.[1]?.trim() || null;

        const companyMatch = script.match(
          /(?:calling from|from)\s+([A-Z][^.!?\n,]+?)(?:\.|!|\?|,|\s+and\b|$)/i
        );
        // Reject matches that are just the agent's own name (false positives)
        const raw = companyMatch?.[1]?.trim() || null;
        scriptCompanyName = raw && raw !== scriptAgentName ? raw : null;
      }

      // ── User (agent) data ────────────────────────────────────────────────────
      // Priority: campaign.agentName → script extraction → user.firstName → 'Alex'
      let agentName   = (c.agentName as string | undefined)?.trim() || scriptAgentName || 'Alex';
      // Priority: user.companyName → script extraction → campaign name → 'NIJVOX'
      let companyName = scriptCompanyName || campaignName || 'NIJVOX';
      try {
        const userId = c.userId?.toString?.() || '';
        if (userId) {
          const user = await storage.getUser(userId);
          if (user) {
            agentName   = (c.agentName as string | undefined)?.trim()
                       || scriptAgentName
                       || (user as any).firstName?.trim()
                       || agentName;
            companyName = (user as any).companyName?.trim()
                       || scriptCompanyName
                       || campaignName
                       || 'NIJVOX';
          }
        }
      } catch (userErr) {
        logger.warn('Could not load user data — using defaults', { error: String(userErr) });
      }

      // ── Caller (lead) metadata ───────────────────────────────────────────────
      // Look up the lead whose phone matches ctx.phone so the greeting can
      // address the caller by name and the KB can reference their company.
      let callerMeta: CallerMetadata | undefined;
      try {
        if (ctx.phone) {
          const userId = c.userId?.toString?.() || '';
          if (userId) {
            const leads = await storage.getLeads(userId, ctx.campaignId);
            const normalizedCtxPhone = normalizePhoneNumber(ctx.phone);
            const matchedLead = leads.find((l) => {
              try {
                return normalizePhoneNumber(l.phone) === normalizedCtxPhone;
              } catch {
                return l.phone === ctx.phone;
              }
            });
            if (matchedLead) {
              const nameParts  = (matchedLead.name || '').trim().split(/\s+/);
              callerMeta = {
                firstName: nameParts[0] || undefined,
                company:   (matchedLead as any).company?.trim() || undefined,
                note:      (matchedLead as any).notes?.trim() || undefined,
              };
              logger.info('Caller identified from lead record', {
                leadName:    matchedLead.name,
                leadCompany: (matchedLead as any).company || '(none)',
              });
            }
          }
        }
      } catch (leadErr) {
        logger.warn('Could not look up lead by phone — proceeding without caller metadata', {
          error: String(leadErr),
        });
      }

      // ── Build product description: what the AI is selling ───────────────────
      // Combine additionalContext + first KB chunk so the AI has real product
      // knowledge even when additionalContext is just company background.
      const kbSummary = kbChunks.length > 0 ? kbChunks[0].substring(0, 500) : '';
      const productDescription = [additionalContext, kbSummary]
        .filter(Boolean)
        .join('\n') || campaignName || 'our product';

      // ── Build PolicyConversationContext ──────────────────────────────────────
      policyContext = {
        agentName,
        companyName,
        productDescription,
        campaignGoal:       goalDescription,
        campaignType,
        language,
        existingScript:     script || undefined,
        caller:             callerMeta,
        knowledgeBase:      kbChunks.length > 0 ? kbChunks : undefined,
      };

      logger.info('PolicyConversationContext built — Conversation Engine active', {
        agentName,
        companyName,
        campaignGoal:  policyContext.campaignGoal,
        campaignType,
        language,
        hasScript:     !!policyContext.existingScript,
        kbChunks:      kbChunks.length,
        hasCaller:     !!callerMeta,
        callerName:    callerMeta?.firstName || '(unknown)',
      });

    } else {
      logger.warn('Campaign not found — will use minimal fallback instructions', {
        campaignId: ctx.campaignId,
      });
      fallbackInstructions = 'You are a professional sales agent on an outbound phone call. Speak naturally and concisely. Ask one question at a time.';
    }
  } catch (err) {
    logger.warn('Failed to load campaign data — will use minimal fallback instructions', {
      campaignId: ctx.campaignId,
      error: String(err),
    });
    fallbackInstructions = 'You are a professional sales agent on an outbound phone call. Speak naturally and concisely. Ask one question at a time.';
  }

  // ── Step 2: Open a real provider session ────────────────────────────────────
  //
  // When `policyContext` is provided, `OpenAIRealtimeProvider.openSession()`
  // creates a `ConversationSessionContext` which:
  //  - Generates the initial system instruction via ConversationPolicyBuilder
  //  - Updates instructions after every agent turn (stage-specific guidance)
  //  - Tracks memory, objections, and stage progression
  //
  // This is the single most important line for making the conversation feel
  // like two humans talking — without it, the AI gets no turn-by-turn guidance.
  const provider = ctx.runtime.resolver.llm() as unknown as OpenAIRealtimeProvider;
  console.log(`[V2 TRACE] 5. OpenAIRealtimeProvider.openSession()  sessionId=${ctx.sessionId}  policyEngine=${policyContext ? 'ON' : 'OFF (fallback)'}`);

  const providerSession = policyContext
    ? provider.openSession({ instructions: '', policyContext, traceSessionId: ctx.sessionId })
    : provider.openSession({ instructions: fallbackInstructions, traceSessionId: ctx.sessionId });

  logger.info('Provider session opened (unconnected — bridge will connect it)', {
    sessionId:    ctx.sessionId,
    policyEngine: policyContext ? 'active' : 'fallback',
  });

  // ── Step 3: Create a fresh audio engine for this call's pipeline ─────────────
  //
  // This engine is independent of the stub AudioEngine that was placed inside
  // the MediaSession at SessionFactory time.  RuntimeIntegration manages this
  // engine's lifecycle via start() / stop() / destroy().
  const audioEngine = createAudioEngine();

  // ── Step 4: Assemble the full RuntimeIntegration ────────────────────────────
  const integration = IntegrationFactory.create({
    sessionId:    ctx.sessionId,
    mediaSession: ctx.mediaSession,
    audioEngine,
    transport:    ctx.transportGateway,
    providerSession,
    logger:       ctx.runtime.resolver.logger(),
  });

  // ── Step 5: Start the integration ───────────────────────────────────────────
  //   • AudioEngine starts
  //   • RealtimeBridge.connect() → provider WebSocket opens → TurnDiagnosticsCollector attaches
  //   • MediaSession.initialize() / start() → transitions to ACTIVE (enables InboundAudioFlow)
  //   • InboundAudioFlow and OutboundAudioFlow start
  //   • SessionSupervisor starts
  await integration.start();

  logger.info('RuntimeIntegration started — Conversation Engine is live', {
    sessionId:    ctx.sessionId,
    policyEngine: policyContext ? 'active' : 'fallback',
  });

  // ── Step 5.5: One-shot audio capture (diagnostic) ────────────────────────────
  // Attaches ONCE per process lifetime. Captures OpenAI output_audio.delta bytes
  // and Exotel-bound bytes for the first call only, then writes:
  //   logs/openai-audio.raw, logs/openai-audio.wav, logs/exotel-audio.raw
  if (!_captureAttached) {
    _captureAttached = true;
    attachOneCallAudioCapture(providerSession, ctx.transportGateway, ctx.sessionId);
  }

  // ── Step 6: Register cleanup on transport disconnect ─────────────────────────
  //
  // When Exotel closes the WebSocket, TransportGateway emits
  // `transport.disconnected`.  Stopping the integration here guarantees
  // RealtimeBridge.disconnect() fires, which:
  //   • detaches TurnDiagnosticsCollector
  //   • prints the [TURN-DIAGNOSTICS] CALL SUMMARY
  //   • persists the JSON log to logs/call-diagnostics/
  const onDisconnected = (event: TransportDisconnectedEvent): void => {
    if (event.sessionId !== ctx.sessionId) return;

    ctx.transportGateway.off('transport.disconnected', onDisconnected);

    logger.info('Transport disconnected — stopping RuntimeIntegration', {
      sessionId: ctx.sessionId,
      code: event.code,
      reason: event.reason,
    });

    integration.stop('transport_disconnected').catch(() => {
      integration.shutdown();
    });
  };

  ctx.transportGateway.on('transport.disconnected', onDisconnected);

  return integration;
}
